### ISSUE TITLE
Can i exclude some models from FLUENT_DASHBOARD_APP_GROUPS? 

### ISSUE THREAD

**Issue by madEng84** [edoburu/django-fluent-dashboard#11]
This is not a bug, but a new-feature request (if not implemented)
As i have written in the title, can i exclude some models from FLUENT_DASHBOARD_APP_GROUPS?

FLUENT_DASHBOARD_APP_GROUPS = (
    (gettext('Administration'), {
        'models': (
            'django.contrib.auth._',
            'django.contrib.sites._',
        ),
        'collapsible': True,
    }),
    (gettext('Poll Management'), {
        'models': (
            'project.apps.news.*',
            'project.apps.polls.poll', # This does not display anything
        ),
        'collapsible': True,
    }),
)

I can't see an help in the documentation
Thanks in advance

**Comment by mhipo1364** [comment]
:+1:
