### ISSUE TITLE
Fresh installation of dashboard crashes after installing fluent-pages

### ISSUE THREAD

**Issue by LiquidPL** [edoburu/django-fluent-dashboard#13]
A fresh, Python 3, Django 1.8.2 installation for fluent-dashboard seems to stop working after installing fluent-pages, with an error:

AttributeError at /admin/fluent_pages/page/
'dict' object has no attribute 'iteritems'

Traceback: http://dpaste.com/13X11MY

**Comment by vdboor** [comment]
This is fixed, thanks to PR #13
